In [23]:
# Import Libraries
import joblib
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn import linear_model, model_selection, metrics
import re #regular expressions
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from datetime import datetime
from nltk.tokenize import word_tokenize
from nltk import ngrams
from nltk.corpus import stopwords
import string
import nltk

In [24]:
# Stopwords set defined
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

#Function to remove irrelevant data
def clean_tweet(tweet):

    # Capital letters to lowercase
    tweet = tweet.lower()
    # Remove URLs
    tweet = re.sub(r'http\S+', '', tweet)
    # Remove user mentions
    tweet = re.sub(r'@[^\s]+', '', tweet)
    # Remove hashtags
    tweet = re.sub(r'#([^\s]+)', r'\1', tweet)
    # Remove punctuation
    tweet = re.sub('[%s]' % re.escape(string.punctuation), '', tweet)
    # Remove #RT
    tweet = re.sub('rt','',tweet)
    # Remove stopwords
    tweet = ' '.join([word for word in tweet.split() if word not in stop_words])
    # Remove numbers
    tweet = re.sub('[0-9]+', '', tweet)
    #Remove non-letters
    tweet = re.sub(r"[^A-Za-z0-9()!?\'\`\"]", " ", tweet)
    #Remove letters from other languages
    tweet = re.sub(r'[^\x00-\x7F]+', '', tweet)

    return tweet

#Function to add keywords
def clean_keyword(keyword):

    # Convert to string and replace %20 for space
    return str(keyword).replace('%20',' ')

# Import data
df = pd.read_csv("../input/nlp-getting-started/train.csv")

# We apply the fuction to remove irrelevant data to the keywords column of the train dataset
df['keyword'] = [clean_keyword(keyword) for keyword in df['keyword']]

# We apply the function to remove irrelevant data to the text column of the train dataset
df['text'] = [clean_tweet(tweet) for tweet in df['text']]

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/anna_verbytska/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [25]:
df.head(50)

,id,keyword,location,text,target
0,1,nan,NaN,deeds reason eahquake may allah forgive us,1
1,4,nan,NaN,forest fire near la ronge sask canada,1
2,5,nan,NaN,residents asked shelter place notified officer...,1
3,6,nan,NaN,people receive wildfires evacuation orders ca...,1
4,7,nan,NaN,got sent photo ruby alaska smoke wildfires pou...,1
5,8,nan,NaN,rockyfire update california hwy closed direct...,1
6,10,nan,NaN,flood disaster heavy rain causes flash floodin...,1
7,13,nan,NaN,im top hill see fire woods,1
8,14,nan,NaN,theres emergency evacuation happening building...,1
9,15,nan,NaN,im afraid tornado coming area,1
10,16,nan,NaN,three people died heat wave far,1
11,17,nan,NaN,haha south tampa getting flooded hah wait seco...,1
12,18,nan,NaN,raining flooding florida tampabay tampa days...,1
13,19,nan,NaN,flood bago myanmar arrived bago,1
14,20,nan,NaN,damage school bus multi car crash breaking,1
15,23,nan,NaN,whats man,0
16,24,nan,NaN,love fruits,0
17,25,nan,NaN,summer lovely,0
18,26,nan,NaN,car fast,0
19,28,nan,NaN,goooooooaaaaaal,0
20,31,nan,NaN,ridiculous,0
21,32,nan,NaN,london cool,0
22,33,nan,NaN,love skiing,0
23,34,nan,NaN,wonderful day,0
24,36,nan,NaN,looooool,0
25,37,nan,NaN,wayi cant eat shit,0
26,38,nan,NaN,nyc last week,0
27,39,nan,NaN,love girlfriend,0
28,40,nan,NaN,cooool,0
29,41,nan,NaN,like pasta,0
30,44,nan,NaN,end,0
31,48,ablaze,Birmingham,wholesale markets ablaze,1
32,49,ablaze,Est. September 2012 - Bristol,always try bring heavy metal,0
33,50,ablaze,AFRICA,africanbaze breaking newsnigeria flag set abla...,1
34,52,ablaze,"Philadelphia, PA",crying set ablaze,0
35,53,ablaze,"London, UK",plus side look sky last night ablaze,0
36,54,ablaze,Pretoria,mufc theyve built much hype around new acquisi...,0
37,55,ablaze,World Wide!!,inec office abia set ablaze,1
38,56,ablaze,NaN,barbados bridgetown jamaica two cars set abla...,1
39,57,ablaze,Paranaque City,ablaze lord,0
40,59,ablaze,Live On Webcam,check nsfw,0
41,61,ablaze,NaN,outside youre ablaze alive youre dead inside,0
42,62,ablaze,milky way,awesome time visiting cfc head office ancop si...,0
43,63,ablaze,NaN,soooo pumped ablaze,0
44,64,ablaze,NaN,wanted set chicago ablaze preaching hotel,0
45,65,ablaze,NaN,gained followers last week know stats grow,0
46,66,ablaze,"GREENSBORO,NORTH CAROLINA",west burned thousands wildfires ablaze califor...,1
47,67,ablaze,NaN,building perfect tracklist life leave streets ...,0
48,68,ablaze,Live On Webcam,check nsfw,0
49,71,ablaze,England.,first night retainers quite weird better get u...,0